test: split out installation test from system-test
googleapis/nodejs-bigquery pull request #345
Opened 2019-02-05 22:51 UTC by kinwa91

Split out install-test as a separate npm run-script instead of bundling
with system-test.

This helps unblock VPCSC testing since it can't fetch external
dependencies with npm install when installation test does npm pack

2019-02-06 19:22 UTC, callmehiphop approved these changes

2019-02-06 19:24 UTC, JustinBeckwith requested changes
Instead of this - could we do the thing you did in storage where we looked for an env var, and did an explicit skip?  I don't want the kokoro configs straying if we can at all avoid it.

2019-02-07 22:26 UTC, kinwa91 commented
I changed it to use the environment variable to determine whether or not to skip install-test, but I still kept it split out

2019-02-08 02:42 UTC, JustinBeckwith approved these changes

2019-02-15 00:03 UTC, merged