fix: Detect Geography type during parameterized query
googleapis/nodejs-bigquery pull request #877
Opened 2020-10-19 16:07 UTC by steffnay

Adds support for detecting a Geography value's type during parameterized query.

- [x] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

🦕

2020-10-19 16:43 UTC, JustinBeckwith approved these changes

2020-10-19 17:07 UTC, stephenplusplus requested changes

2020-10-19 17:07 UTC, stephenplusplus commented on src/bigquery.ts
> +      return (
I don't believe this part is tested.

2020-10-26 13:12 UTC, steffnay commented on src/bigquery.ts
> +      return (
updated.

2020-10-27 17:37 UTC, stephenplusplus approved these changes

2020-10-28 15:03 UTC, merged